Default: &defaults
  database: kancolle.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: kancolle_test.sqlite3
  <<: *defaults

Staging:
  database: kancolle_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: kancolle_production.sqlite3
  poolsize: 100
  <<: *defaults
